version: "3.9"

services:
  db:
    container_name: postgres-do-an
    image: kartoza/postgis:14-3.2
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis,doan
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5433:5432"
    restart: always

  redis:
    container_name: redis-do-an
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-do-an-data:/data

volumes:
  dbbackups:
  postgis-data:
  redis-do-an-data:
